### ISSUE TITLE
Problem with calendar ics files in Safari

### ISSUE THREAD

**Issue by Shashi456** [acl-org/acl-2020-virtual-conference#486] opened 2020-07-05 17:27 UTC
Hi, I think there might be some problem with the calendar ics file for the paper QA sessions. For example, an event is on 09:00-10:00 GMT / 11:00-12:00 CEST according to the webpage, and my time zone is CEST (2 hours ahead of GMT/UTC), the downloaded ics file has the attribute DTSTART:20200706T110000Z, with the suffix "Z" meaning the UTC time, so it ends up with 13:00-14:00 in my calendar.
[Reported by Xiang Yu]

**Comment by GuyAglionby** [comment] 2020-07-05 22:06
The only session on 6 July 9-10am GMT is session 2B - I downloaded the .ics for [this paper](https://virtual.acl2020.org/paper_main.157.html) and can't replicate the issue:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
URL:https://virtual.acl2020.org/paper_main.157.html
DTSTART:20200706T090000Z
DTEND:20200706T100000Z
[...]
```

Do you know which paper the user was having trouble with in particular?

**Comment by Shashi456** [comment] 2020-07-06 07:19
Related issue #509

**Comment by Shashi456** [comment] 2020-07-06 08:15
> [Website] The times in the Google calendar link and on the page do not match. They are off by two hours. The time on the page is the one in the email, but I am now unsure when to be in the session
https://virtual.acl2020.org/paper_main.154.html
- Dirk hovy

**Comment by hao-fang** [comment] 2020-07-06 21:33
Copied from #509 
> This problem only appears in Safari, using Chrome is fine.

**Comment by hao-fang** [comment] 2020-07-10 02:58
Close this b/c cannot reproduce the bug.. we can re-open if it happens again

**Closed by hao-fang** 2020-07-10 02:58 UTC
