### ISSUE TITLE
Better way to embed videos for workshop papers

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#416] opened 2020-07-03 20:37 UTC
[Website] I wish you hadn't embedded the videos in the main WiNLP page. It takes so long to be loaded.

https://acl2020.rocket.chat/channel/helpdesk?msg=FskwnezzHbjRMJtF7

**Comment by raosudha89** [comment] 2020-07-03 21:20
This is a duplicate of https://github.com/acl-org/acl-2020-virtual-conference/issues/370

**Closed by raosudha89** 2020-07-03 21:20 UTC
Labels: enhancement, priority:low, volunteer needed
